# There needs to be some kind of way to register and serialize data
# We could take an enum of game object types as a generic parameter and
# maybe use fields to discriminate variants

# Thing is I really don't like how this creates a fairly uninteresting file
# that is just a bunch of [[node]] entryies. It could be nice to use the tag
# to change type of node

[[node]]
type = "Light"
power = 0.1

[[node]]
type = "Player"

[[scripts]]

